### ISSUE TITLE
Error using multiple events with .json()

### ISSUE THREAD

**Issue by bluepuma77** [tncrazvan/sveltekit-sse#25]
I have been trying all day to get this to work together, but it seems to not work.

It's the `Chat` component ([link](https://github.com/bluepuma77/sveltekit-sse-chat-example/blob/main/src/routes/Chat.svelte)) of my demo app. 

When using `emit('users', JSON.stringify(getRoomUsers(room)))` and
```
    const users = connection.select("users").json(
        function onJsonParseError({error, currentRawValue, previousParsedValue}){
            console.error(`Could not parse "${currentRawValue}" as json.`, error)
            return previousParsedValue  // this will be the new value of the store
        }
    )
```
I receive error `Could not parse users as json`

**Comment by bluepuma77** [comment]
I created a Stackblitz REPL, the most basic version seems to work ([link](https://stackblitz.com/edit/sveltejs-kit-template-default-zissfx?file=src%2Froutes%2Fevents%2F%2Bserver.js,src%2Froutes%2F%2Bpage.svelte)), need to dig deeper.

**Comment by bluepuma77** [comment]
Now I added the new locking and pubsub to the basic example and it's not working anymore ([link](https://stackblitz.com/edit/sveltejs-kit-template-default-tf6lqb?file=src%2Froutes%2Fevents%2F%2Bserver.js,src%2Froutes%2FEvents.svelte)).

**Comment by bluepuma77** [comment]
The reduced example works with a single `emit(data)` and not `emit(eventName, data)` ([link](https://stackblitz.com/edit/sveltejs-kit-template-default-faws1f?file=src%2Froutes%2Fevents%2F%2Bserver.js,src%2Froutes%2FEvents.svelte)).

Then I can receive without `select()`: 
```
const connection = source('/events')
  const value1 = connection.json(...)
```

**Comment by tncrazvan** [comment]
Hi @bluepuma77 ,
I'll take a look at this soon.

**Comment by tncrazvan** [comment]
> Now I added the new locking and pubsub to the basic example and it's not working anymore ([link](https://stackblitz.com/edit/sveltejs-kit-template-default-tf6lqb?file=src%2Froutes%2Fevents%2F%2Bserver.js,src%2Froutes%2FEvents.svelte)). This time I don't see any JSON parse error, but no SSE events are shown.

You're using `event()` instead of `events()` to emit your messages.

The `event` function is meant for creating a single event over a single connection, more fit for http2 connections.

It gives you an `EmitterOfOneEvent` 
![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/85ee58bf-e60f-4880-bfe9-aaf3d3d6d083)

Which takes just 1 string as a parameter
![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/6494c1f1-0b7f-4a1f-9647-06565ff0e187)


What you need is `events()` which gives you an `EmitterOfManyEvents`.
![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/817c6670-d7b2-4b62-881a-41994ba77f5d)
![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/9601a0d5-10d4-45ff-96d8-de87427d5e82)

**Comment by tncrazvan** [comment]
@bluepuma77 here's the stackblitz example adjusted to use `events` instead of `event` ([link](https://stackblitz.com/edit/sveltejs-kit-template-default-ggalns?file=src%2Froutes%2Fevents%2F%2Bserver.js)).

**Comment by bluepuma77** [comment]
Thanks for this, @tncrazvan ! Is it possible to log or throw an error when someone uses `emit(name, data)` with (single) `event`? I am sure there will be others that will make the same mistake.

**Comment by tncrazvan** [comment]
@bluepuma77 no, that's not an appropriate solution.

You need some linter for your project.
If you do that, you'll get proper warnings about types, parameters and so on.

I just setup ESLint on the fork I made of your chatroom example, and this is the result

![Peek 2024-01-27 19-52](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/b90bd884-f759-4301-9d46-ee2c7b772962)

As you can see, you get an actual linting error saying `event()` expects only 1 argument.
You can even make it so that svelte doesn't build at all if there are errors, that is up to you though.

Obviously you don't have to use my ESLint configuration, there's even one that comes with any default sveltekit project if pick the option during creation

![image](https://github.com/tncrazvan/sveltekit-sse/assets/6891346/26f1aad0-8c9f-4511-a43a-54497c2434f0)

I just sent you another PR setting up ESLint for you on that project ([link](https://github.com/bluepuma77/sveltekit-sse-chat-example/pull/2)).

There's not much else I can do though, setting a logger for the `emit()` function might actually have a performance hit.
I'm aware that speaking of "performance" in JavaScript is laughable, but still, it doesn't seem appropriate when there are other ways (with zero runtime cost) to prevent such mistakes.

I'm keeping this issue closed for now.
