### ISSUE TITLE
docs: Explain requirement for all logic within `start()`

### ISSUE THREAD

**Issue by oscarhermoso** [tncrazvan/sveltekit-sse#36]
On the README page, it states that on the server, all logic must be contained within the `events::start` call:

> Due to how the [beacon api](https://github.com/kedyou/sveltekit-sse#beacon) works, you must write all your logic within the start() function while on the server.

Would it be possible to explain the reason and consequences of not following this?

**Comment by tncrazvan** [comment]
When you invoke `source("/events")` you create an http request to `POST /events` which upgrades to an sse request.
This http response of the server will contain a header `X-SSE-ID`, which identifies the sse stream.
At the same time, the server will schedule the given event to be closed and destroyed destroyed after some [T milliseconds](https://github.com/tncrazvan/sveltekit-sse/blob/a183d9d9857b1f44da498520f263b38f5c491439/src/lib/events.js#L230-L236).

While all of that is going on on the server, on the client side, every [T milliseconds](https://github.com/tncrazvan/sveltekit-sse/blob/a183d9d9857b1f44da498520f263b38f5c491439/src/lib/source.js#L149), you browser will send a beacon request to `POST /events?x-sse-id=some-id-given-by-the-server`, which, as you can see, contains the same stream id as a query string.

> [!NOTE]
> We should probably use a header instead of a query string in the future.\
> This will probably be the next update I'll make.

The server will validate this id.\
If it is correct, meaning it is internally [mapped](https://github.com/tncrazvan/sveltekit-sse/blob/a183d9d9857b1f44da498520f263b38f5c491439/src/lib/events.js#L69-L72), it will [clear the old schedule](https://github.com/tncrazvan/sveltekit-sse/blob/a183d9d9857b1f44da498520f263b38f5c491439/src/lib/events.js#L266) for destroying the stream, and [create a new one](https://github.com/tncrazvan/sveltekit-sse/blob/a183d9d9857b1f44da498520f263b38f5c491439/src/lib/events.js#L271C7-L271C16).

This how we detect that a user has closed the stream on their side.

Both beacon and sse request share the same endpoint `/events`.
If you put your logic in the body of the POST function, instead of within the `start()` callback, then that code will be executed every `T milliseconds`, which is a waste of resources, because beacon request don't need and don't even wait for the server to respond. They're meant to be lightweight requests, mainly used for analytics.

[Beacon requests](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#description) are a hack, because SvelteKit doesn't have an API that informs us, the userland, when a client has canceled an http request, unlike other frameworks like dotnet for example, which [has a very explicit solution for this](https://medium.com/codenx/cancellation-tokens-in-asp-net-core-6a83b7979dd8). Hopefully we'll get something like that in SvelteKit some day.

The reason the beacon and the sse stream share the same endpoint is because this library promises easy use of sse.
Requiring the userland to manage their own streams is not "easy to use".

**Comment by oscarhermoso** [comment]
Thank you, that makes a lot of sense now
