### ISSUE TITLE
`emit` not working more than once

### ISSUE THREAD

**Issue by BearToCode** [tncrazvan/sveltekit-sse#40]
I've just copied the example:

```ts
export function POST({ request }) {
  return events({
    request,
    async start({emit}) {
      while(true){
        emit('message', 'hello world')
        await delay(1000)
      }
    },
  })
}
```

And did the following on the client:

```svelte
<script>
  const value = source('/sse/chat').select('message');

  value.subscribe((message) => {
    console.log(message);
  });
</script>
```

But `'hello world'` is being logged only once! [example](https://www.sveltelab.dev/288z1aksb2gx0jw?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte)

**Comment by tncrazvan** [comment]
Hello @BearToCode ,

The `emit` function is working correctly in this case.

The behavior you're experiencing is the default behavior of svelte's stores.
A svelte store does not forward duplicate values, it checks for equality.
If value `N+1` is equal to value `N`, then the value of the store won't change, thus your subscribe function won't trigger.

That's just how svelte stores work.
See [reference here](https://github.com/sveltejs/svelte/blob/4479b8c6f316edc29881e97f6160b347fc35217e/packages/svelte/src/store/index.js#L54-L70).

This library does provide a solution.
What you're looking for is `transform()`

```svelte
<script>
  const value = source('/sse/chat').select('message').transform((message) => {
    console.log(message);
    return message
  });
</script>
```

Make sure you update to the latest `0.12.1` version to get this feature.

---

I agree the readme is a bit confusing since it's emitting a static string, so I've updated it to emit a variable string.

Let me know if this addresses your issue.

**Comment by BearToCode** [comment]
My bad, now it's working. Grazie mille :)
