### ISSUE TITLE
Add a way to support adding onMessage hooks to source()

### ISSUE THREAD

**Issue by Sheco** [tncrazvan/sveltekit-sse#47]
Hello, the current client-side code only supports fetching the latest/current value, for example:

```
<script>
  // src/routes/+page.svelte
  import { source } from 'sveltekit-sse'
  const value = source('/custom-event').select('message')
</script>

{$value}
```

Would it make sense to support using `consume`'s onMessage hook in `source()`? something like the following?

```
<script>
  // src/routes/+page.svelte
  import { source } from 'sveltekit-sse'
  let log = $state([])
  source('/custom-event').listen('message', (event) => {
     log.push(event.data)
  })
</script>

{#each log as message}
  {message}
{/each}
```

**Comment by tncrazvan** [comment]
Hello @Sheco 

Try this

```svelte
<script>
  // src/routes/+page.svelte
  import { source } from 'sveltekit-sse'
  let log = $state([])
  source('/custom-event').subscribe((data) => {
     log.push(data)
  })
</script>

{#each log as message}
  {message}
{/each}
```

> [!NOTE]
> I haven't actually tested this code with Svelte 5, but it should work.

Is this what you're looking for?

**Comment by Sheco** [comment]
Nevermind, it's perfect, it was indeed a silly error on my side.

Thank you very much! You're the best, you can close this issue.

**Comment by gregorvand** [comment]
Thanks for all of the great answers @razshare 

I was going to post a new question however it is virtually identical to this, however not using Svelte 5 - I have not reliably been able to find a way to get updates using `.subscribe..` 

in the context of a changestream listener, that I hoped to just post an event to client each time it happens:

ie server:

```
return produce(async function start({ emit }) {
      current_change_stream?.on('change', (change) => {
        console.log('Change detected here too', change);
        emit('authlines', `authline-check`)
      });
    });
 ```
 
 client
 ```
 source('/custom-events').select('authlines').subscribe((event) => {
    console.log('event', event);
  });
  ```
  
  which works, but only for the first changestream change event, not subsequent
  
  many thanks

**Comment by razshare** [comment]
Hello @gregorvand , you might be experiencing a behavior of svelte's stores of which few people seem to be aware of (or rather they seem to have forgotten with time), which is: svelte stores filter out duplicate values.

When you `emit('authlines', 'authline-check')`, the data is actually being sent over to your client (check the network tab), but the svelte store which you're subscribing to is detecting that all subsequent values are duplicates of the previous, and doesn't trigger your subscriber.

That's just how svelte stores work.

Take for example this code
![Peek 2024-09-24 18-10](https://github.com/user-attachments/assets/40a1dec5-cd34-4061-9238-f2749468cdef)


There are a few workarounds, the simplest I think is to include something unique in your producer message, or maybe something "unique enough" for your use case, like the current time stamp.

Something like this should do the trick.
```js
return produce(async function start({ emit }) {
      current_change_stream?.on('change', (change) => {
        console.log('Change detected here too', change);
        emit('authlines', `authline-check- ${Date.now()}`)
      });
});
```

So in the example above, the solution would look something like this
![Peek 2024-09-24 18-13](https://github.com/user-attachments/assets/a41f0d64-b257-48d1-bac4-29f0da40d26d)

and it should start working as you expect it to.

If you don't want to append extra data to your payloads, another solution is to use `source::select::transform` on your client side, to inject this additional unique identifier.

So the only thing you have to change is to add a `transform` step on your client side

```svelte
<script>
	import { source } from 'sveltekit-sse';
	source('/custom-events')
		.select('message')
		.transform((data) => `${data} - ${Date.now()}`)
		.subscribe((value) => console.log(value));
</script>
```

The result should look something like this
![Peek 2024-09-24 18-43](https://github.com/user-attachments/assets/322ba6e6-d685-41f3-a0e2-019b7f455fa3)

This way you don't send the extra data from your server.

Though personally, I wouldn't bother doing the transformation client side.
That's because normally, in more complex apps you would want to structure your data somehow, and that usually involves some kind of identifier, not just for logic purposes but also for debugging purposes.

Identifiers are just useful.

Let me know if this answers your question.

PS: I've also just noticed the `transform()` method was wrongly typed, so I just released [a fix](https://github.com/razshare/sveltekit-sse/releases/tag/0.13.6).

**Comment by gregorvand** [comment]
@razshare thank you SO much! And for the detailed explanation. 
I am a bit embarrassed to have forgotten about how stores work in that regard, and your idea of just appending the `Date.now()` on the producer side has indeed completely fixed it.

Thanks again!
